accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.user_register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/',views.user_logout, name='logout'),
]

chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

chat_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls', namespace='chat')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser

from .managers import UserManager


class User(AbstractBaseUser):
    username = models.CharField(max_length=150, unique=True)    
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []


    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

chat/models.py
from django.db import models


class Message(models.Model):
    username = models.CharField(max_length=255)
    room = models.CharField(max_length=255)
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('date',)

accounts/forms.py
from django import forms


class UserLoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control rounded-pill', 'placeholder': 'username'}
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control rounded-pill', 'placeholder': 'password'}
        )
    )


class UserRegistrationForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control rounded-pill', 'placeholder': 'username'}
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control rounded-pill', 'placeholder': 'password'}
        )
    )
    password_confirm = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control rounded-pill', 'placeholder': 'confirm password'}
        )
    )

    def clean(self):
        cleaned_data = super(UserRegistrationForm, self).clean()
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')
        if password and password_confirm:
            if password != password_confirm:
                msg = "The two password fields must match."
                self.add_error('password_confirm', msg)
        return cleaned_data

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout

from .forms import UserRegistrationForm, UserLoginForm
from .models import User


def user_register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            check_user = User.objects.filter(username=data['username'])
            if not check_user:
                user = User.objects.create_user(
                    data['username'], data['password']
                )
                return redirect('accounts:login')
    else:
        form = UserRegistrationForm()
    context = {'form':form}
    return render(request, 'register.html', context)


def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = authenticate(
                username=data['username'], password=data['password']
            )
            if user is not None:
                login(request, user)
                return redirect('chat:index')
            else:
                return redirect(request.META.get('HTTP_REFERER'))
    else:
        form = UserLoginForm()
    context = {'form': form}
    return render(request, 'login.html', context)


def user_logout(request):
    logout(request)
    return redirect('accounts:login')

chat/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from .models import Message


def index(request):
    return render(request, 'index.html')


@login_required
def room(request, room_name):
    messages = Message.objects.filter(room=room_name).all()
    context = {
        'room_name': room_name,
        'username': request.user.username,
        'messages':messages
    }
    return render(request, 'room.html', context)

accounts/templates/login.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <h3>Login</h3>
        <hr class="text-muted">
        <form method="POST">
            {% csrf_token %}
            <div>
                {{ form.username }}
            </div>
            <div class="mt-2">
                {{ form.password }}
            </div>
            <div class="form-group">
                <button class="btn btn-outline-primary rounded-pill mt-3 w-100" type="submit">Submit</button>
            </div>
        </form>
        <div class="pt-3">
            <small class="text-muted">
                Need an Account? <a class="text-decoration-none" href="{% url 'accounts:register' %}">Create account</a>
            </small>
        </div>
    </div>
{% endblock content %}

accounts/templates/register.html
{% extends "base.html" %}
{% block content %}
<div>
    <h4>Create Account</h4>
    <hr class="text-muted">
    <form method="POST">
        {% csrf_token %}
        <div>
            {{ form.username }}
        </div>
        <div class="mt-2">
            {{ form.password }}
        </div>
        <div class="mt-2">
            {{ form.password_confirm }}
        </div>
        <div class="form-group">
            <button class="btn btn-outline-primary rounded-pill mt-3 w-100" type="submit">Submit</button>
        </div>
    </form>
    <div class="pt-3">
        <small class="text-muted">
            Have an Account? <a class="text-decoration-none" href="{% url 'accounts:login' %}">Log in</a>
        </small>
    </div>
</div>
{% endblock content %}

chat/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <title>Djnago Chat App</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <div class="row d-flex align-items-center justify-content-center" style="height: 500px">
        <div class="col-md-4"></div>
        <div class="col-md-4">
        {% block content %}{% endblock %}
        </div>
        <div class="col-md-4"></div>

      </div>
    </div>
  </body>
</html>

chat/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="">
        <input class="form-control rounded-pill" type="text" placeholder="Room name" id="room-name-input">
    </div>
    <div class="mt-2">
        <a class="btn btn-primary w-100 rounded-pill" id="room-name-submit">Join Room</a>
    </div>
<script src="{% static 'index.js' %}"></script>
{% endblock %}

chat/templates/room.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h3 class="ms-2 text-muted text-capitalize">{{room_name}}</h3>
    <div style="border-radius: 30px;" class="border p-3">
      <div id="chat-messages" style="max-height: 400px; overflow-y: scroll;">
        {% for message in messages %}
        <b>{{ message.username }}</b>: {{ message.content }}<br>
        {% endfor %}
      </div>
    </div>
    <div class="row mt-3">
      <div class="col-md-10">
        <input class="form-control rounded-pill" type="text" placeholder="Write something..." id="chat-message-input" required>
      </div>
      <div style="margin-left: -20px;" class="col-md-1">
        <a class="btn btn-primary rounded-pill" id="chat-message-submit">Send</a>
      </div>
    </div>
{{ room_name|json_script:"json-roomname" }}
{{ username|json_script:"json-username" }}
<script src="{% static 'room.js' %}"></script>
{% endblock %}